export enum Role {
  ADMIN = 'ADMIN',
  USER = 'USER'
}

export enum Income {
  PRONTIPAGOS = 'PRONTIPAGOS',
  MEDICAMENTO = 'MEDICAMENTO'
}

export const conceptList = ["Cobro con tarjeta", "Cobro por transferencia", "Retiro administrativo", "BBVA", "COPPEL", "BANORTE", "BANREGIO", "SCOTIABANK", "OTROS"]

export enum Defaults {
  PRONTIPAGOS = 1,
  MEDICAMENTO = 2
}

export enum ExpenseStages {
  SELECT_EXPENSE_TYPE = 'SELECT_EXPENSE_TYPE',
  PROVIDER_SELECTION = 'PROVIDER_SELECTION',
  SERVICE_SELECTION = 'SERVICE_SELECTION',
  SELLER_SELECTION = 'SELLER_SELECTION',
  OTHER_EXPENSE_REGSTRY = 'OTHER_EXPENSE_REGSTRY',
  NEW_EXPENSE_DETAILS = 'NEW_EXPENSE_DETAILS',
  FINALIZE_EXPENSE_REGISTRY = 'FINALIZE_EXPENSE_REGISTRY'
}

export enum WithdrawalStages {
  SELECT_WITHDRAWAL_STAGE = 'SELECT_WITHDRAWAL_STAGE',
  FINALIZE_WITHDRAWAL_STAGE = 'FINALIZE_WITHDRAWAL_STAGE'
}

export enum ExpenseTypeId {
  SUELDOS = 1,
  RENTA = 2,
  OTROS = 3,
  SERVICIOS = 4,
  PROVEEDORES = 5,
  PROVEEDORES_MEDICAMENTO = 6,
}